{% set name = "nr.preconditions" %}
{% set version = "0.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nr.preconditions-{{ version }}.tar.gz
  sha256: 86b91f9b9500f34b367780c26c60dc17c5f8f5784df38cbed7137b0ea6f3fa4d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0

test:
  imports:
    - nr
    - nr.preconditions
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://git.niklasrosenstein.com/NiklasRosenstein/nr
  summary: Provides simple functions to assert the state of your program.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - NiklasRosenstein
